import { Link } from "react-router-dom";
import { Check, CircleDollarSign, FileCheck2, Mail, ShieldCheck } from "lucide-react";
import SiteLayout from "@/components/layout/SiteLayout";

type TrustPage = "privacy" | "terms" | "contact" | "creator-guidelines" | "payouts";

const pages: Record<TrustPage, { eyebrow: string; title: string; intro: string }> = {
  privacy: { eyebrow: "Privacy", title: "How MakeBetter handles your information", intro: "MakeBetter collects only the information needed to give buyers access to assets, review creator submissions, and keep the marketplace safe." },
  terms: { eyebrow: "Terms of use", title: "Rules for using MakeBetter", intro: "These terms set the basic rules for buyers, creators, and visitors using makebetter.im." },
  contact: { eyebrow: "Contact", title: "Help with a MakeBetter account or asset", intro: "Use the right route below so we can resolve the issue with the relevant account or listing context." },
  "creator-guidelines": { eyebrow: "Creator guidelines", title: "Publish useful AI assets buyers can trust", intro: "MakeBetter is for practical prompts, AI agents, assistants, workflows, templates, API tools, automation assets, and creator resources that help people do better work." },
  payouts: { eyebrow: "Creator earnings", title: "How pricing, commission, and payouts work", intro: "Creators choose the price for their paid assets. MakeBetter keeps a 20% marketplace commission and creators receive 80% of completed net sales." },
};

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => <section className="mt-10 border-t border-white/10 pt-8 first:mt-0 first:border-0 first:pt-0"><h2 className="text-xl font-medium">{title}</h2><div className="mt-3 space-y-3 text-sm leading-7 text-[#CFCFCF]">{children}</div></section>;

export default function TrustPages({ page }: { page: TrustPage }) {
  const meta = pages[page];
  return <SiteLayout><section className="container-mb max-w-4xl pt-12 pb-20 sm:pt-16 sm:pb-24"><div className="eyebrow">{meta.eyebrow}</div><h1 className="mt-5 max-w-3xl text-3xl font-medium leading-[1.08] sm:text-4xl md:text-5xl">{meta.title}</h1><p className="mt-5 max-w-2xl text-base leading-relaxed text-[#CFCFCF] sm:text-lg">{meta.intro}</p><p className="mt-4 text-xs text-white/45">Last updated: July 31, 2026</p><div className="mt-10 card-premium p-5 sm:p-8">{page === "privacy" && <Privacy />}{page === "terms" && <Terms />}{page === "contact" && <Contact />}{page === "creator-guidelines" && <CreatorGuidelines />}{page === "payouts" && <Payouts />}</div></section></SiteLayout>;
}

function Privacy() { return <><Section title="Information we collect"><p>We collect account details such as your email address and name when you sign in, creator application information when you apply to sell, and listing details, previews, and private deliverables when you submit an asset.</p><p>When you request a paid asset that is not yet available for checkout, we also collect the contact details you submit with that request. MakeBetter does not currently charge a payment card for these requests.</p></Section><Section title="How we use it"><p>We use this information to authenticate your account, deliver or manage asset access, review creator applications and submissions, prevent abuse, and reply to support requests.</p></Section><Section title="Who can see it"><p>Public creator profiles and published asset details are visible to marketplace visitors. Private asset deliverables are restricted to the appropriate asset-access flow. Creator applications, unpublished submissions, account details, and paid-access requests are available only to MakeBetter administrators and service providers needed to operate the platform.</p></Section><Section title="Your choices"><p>You can ask us to correct or remove account information where applicable. For an access or privacy request, email <a className="text-[#FFD600] hover:underline" href="mailto:support@makebetter.im">support@makebetter.im</a> from the email connected to your account.</p></Section></>; }
function Terms() { return <><Section title="Using the marketplace"><p>Use MakeBetter lawfully and do not try to bypass access controls, scrape private content, interfere with the platform, or misrepresent your identity. We may limit or remove access that puts the marketplace or its users at risk.</p></Section><Section title="Assets and licenses"><p>Each asset is supplied by its creator. The listing and any attached license describe how it may be used. Buyers must not resell, redistribute, or claim another creator’s asset as their own unless the creator has expressly allowed it.</p></Section><Section title="Free and paid access"><p>Free assets are provided through MakeBetter’s email-based access flow. Paid checkout is currently unavailable: a paid-asset request records interest only, and no payment is taken until MakeBetter launches checkout.</p></Section><Section title="Creator responsibility"><p>Creators must own or have permission to distribute everything they upload, including preview images, prompts, files, links, and template content. MakeBetter may reject, unpublish, or remove assets that are misleading, infringing, unsafe, or not useful to buyers.</p></Section></>; }
function Contact() { return <><div className="grid gap-4 sm:grid-cols-3"><ContactCard icon={<Mail />} title="Account & access" text="Include the email on your MakeBetter account and the asset URL." /><ContactCard icon={<FileCheck2 />} title="Creator support" text="Include your creator profile or asset submission link." /><ContactCard icon={<ShieldCheck />} title="Report an issue" text="Use this for broken links, rights concerns, or suspicious listings." /></div><Section title="Email MakeBetter support"><p>Send your request to <a className="text-[#FFD600] hover:underline" href="mailto:support@makebetter.im">support@makebetter.im</a>. To help us investigate quickly, include the relevant MakeBetter page link and a short description of what happened.</p></Section></>; }
function ContactCard({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="rounded-2xl border border-white/10 bg-black/25 p-5"><div className="text-[#FFD600] [&>svg]:h-5 [&>svg]:w-5">{icon}</div><h2 className="mt-4 font-medium">{title}</h2><p className="mt-2 text-sm leading-6 text-[#CFCFCF]">{text}</p></div>; }
function CreatorGuidelines() { const items = ["Apply as a creator first. Only approved creators can submit assets to the creator dashboard.", "Make the value clear: state who the asset is for, the result it helps achieve, and exactly what is included.", "Use an accurate preview and description. The preview must not expose a private deliverable or promise functionality the asset does not provide.", "Choose the right delivery method: an uploaded file, a stable external link, or private text/prompt content.", "Submit only work you own or are authorized to distribute. Do not upload harmful, deceptive, infringing, or credential-bearing content.", "Every asset is reviewed by MakeBetter before it becomes publicly available. A submission can be returned for changes or rejected."]; return <><Section title="What good MakeBetter assets look like"><p>Useful assets are specific enough that a buyer can understand the job they solve before claiming or requesting access—for example, a cold-email workflow for B2B founders, a support agent prompt system, or a reusable content-repurposing template.</p></Section><Section title="Submission checklist"><ul className="space-y-3">{items.map(item => <li key={item} className="flex gap-3"><Check className="mt-1 h-4 w-4 shrink-0 text-[#FFD600]" /> <span>{item}</span></li>)}</ul></Section><Section title="Ready to contribute?"><p><Link className="text-[#FFD600] hover:underline" to="/creator-signup">Apply to become a creator</Link>, or, if you are already approved, <Link className="text-[#FFD600] hover:underline" to="/creator-dashboard/submit-asset">submit an asset from your dashboard</Link>.</p></Section></>; }
function Payouts() { return <><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-[#FFD600]/20 bg-[#FFD600]/10 p-6"><div className="text-3xl font-medium text-[#FFD600]">80%</div><p className="mt-2 text-sm text-[#CFCFCF]">Creator share of completed net sales</p></div><div className="rounded-2xl border border-white/10 bg-black/25 p-6"><div className="flex items-center gap-2 text-3xl font-medium"><CircleDollarSign className="h-7 w-7 text-[#FFD600]" />20%</div><p className="mt-2 text-sm text-[#CFCFCF]">MakeBetter marketplace commission</p></div></div><Section title="Pricing and commission"><p>You set the public USD price for each paid asset you submit. When a paid sale is completed, MakeBetter retains 20% and allocates 80% to the creator, subject to applicable refunds, taxes, chargebacks, and payment-processing requirements.</p></Section><Section title="Current payment status"><p>Payments and creator payouts are not live yet. Buyers can submit an interest request for paid assets, but MakeBetter does not charge them today and no creator payout is generated from that request.</p></Section><Section title="What happens when payouts open"><p>Approved creators will receive instructions in their dashboard and by email to complete payout setup. We will publish the payout schedule, available countries, minimum payout amount, and required tax/payment details before the first paid checkout goes live.</p></Section></>; }
