-- Demo marketplace content for Phase 1.
-- This file matches 20260517_phase_1_marketplace_schema.sql.
-- It inserts into public.creators and public.assets only. Safe to re-run after
-- a partial insert.

begin;

-- Compatibility for projects that ran the first Phase 1 migration before demo
-- creators were changed to allow null profile_id.
alter table public.creators alter column profile_id drop not null;

with creator_seed (
  slug,
  brand_name,
  niche,
  description,
  tags,
  followers,
  assets_count,
  downloads,
  rating,
  monthly_revenue,
  strengths,
  active
) as (
  values
    (
      'growth-lab',
      'Growth Lab',
      'Ecommerce & growth systems',
      'Growth Lab turns repeatable growth processes into ready-to-use AI assets for founders, marketers, and ecommerce teams.',
      array['Ecommerce', 'Shopify', 'Growth']::text[],
      2400,
      14,
      12400,
      4.9::numeric,
      '~$3.5k/mo',
      array['Validated playbooks', 'Battle-tested with 6-figure stores', 'Constant updates']::text[],
      true
    ),
    (
      'outbound-studio',
      'Outbound Studio',
      'Sales assets and outreach systems',
      'Outbound Studio packages high-converting outbound sequences and sales workflows used by B2B teams.',
      array['Sales', 'Cold Email', 'B2B']::text[],
      1800,
      9,
      8100,
      4.8::numeric,
      '~$3.1k/mo',
      array['Reply-rate tested', 'Personalization at scale', 'CRM-ready']::text[],
      true
    ),
    (
      'rank-better',
      'Rank Better',
      'SEO and content workflows',
      'Rank Better builds the SEO and content workflows behind some of the fastest-growing programmatic sites.',
      array['SEO', 'Content', 'Programmatic']::text[],
      3100,
      18,
      16200,
      4.9::numeric,
      '~$4.2k/mo',
      array['E-E-A-T compliant', 'Topical authority focused', 'Scales to 1000+ pages']::text[],
      true
    )
)
insert into public.creators (
  slug,
  brand_name,
  niche,
  description,
  tags,
  followers,
  assets_count,
  downloads,
  rating,
  monthly_revenue,
  strengths,
  active
)
select
  slug,
  brand_name,
  niche,
  description,
  tags,
  followers,
  assets_count,
  downloads,
  rating,
  monthly_revenue,
  strengths,
  active
from creator_seed
on conflict (slug) do update set
  brand_name = excluded.brand_name,
  niche = excluded.niche,
  description = excluded.description,
  tags = excluded.tags,
  followers = excluded.followers,
  assets_count = excluded.assets_count,
  downloads = excluded.downloads,
  rating = excluded.rating,
  monthly_revenue = excluded.monthly_revenue,
  strengths = excluded.strengths,
  active = excluded.active;

with asset_seed (
  creator_slug,
  slug,
  title,
  product_type,
  category,
  short_description,
  long_description,
  tags,
  status,
  is_free,
  price,
  price_type,
  downloads,
  rating,
  review_count,
  featured
) as (
  values
    (
      'growth-lab',
      'dropshipping-product-research-agent',
      'Dropshipping Product Research Agent',
      'AI Agents',
      'AI Agent - Ecommerce',
      'Find winning products, analyze competitors, uncover demand signals, and generate offer angles in minutes instead of hours.',
      'An end-to-end research agent built for store owners who want a repeatable validation system instead of guessing.',
      array['Shopify', 'Product Research', 'DTC']::text[],
      'published'::public.asset_status,
      false,
      19::numeric,
      'paid'::public.price_type,
      1840,
      4.9::numeric,
      126,
      true
    ),
    (
      'outbound-studio',
      'cold-email-reply-engine',
      'Cold Email Reply Engine',
      'Workflows',
      'Workflow - Sales',
      'An outbound system that researches, personalizes, and writes 100 cold emails in the time it takes to write 5.',
      null,
      array['Cold Email', 'Outbound', 'B2B']::text[],
      'published'::public.asset_status,
      false,
      29::numeric,
      'paid'::public.price_type,
      920,
      4.8::numeric,
      81,
      true
    ),
    (
      'rank-better',
      'seo-cluster-builder',
      'SEO Topical Cluster Builder',
      'Workflows',
      'Workflow - SEO',
      'Generate full topical maps, supporting briefs, and internal linking plans for any niche in one run.',
      null,
      array['SEO', 'Content', 'Briefs']::text[],
      'published'::public.asset_status,
      false,
      24::numeric,
      'paid'::public.price_type,
      1410,
      4.9::numeric,
      102,
      true
    ),
    (
      'growth-lab',
      'tiktok-hook-prompt-pack',
      'TikTok Hook Prompt Pack',
      'Prompts',
      'Prompts - Content',
      '60+ proven hook frameworks adapted into prompts you can run today to script viral short-form video.',
      null,
      array['TikTok', 'Hooks', 'Short-form']::text[],
      'published'::public.asset_status,
      true,
      0::numeric,
      'free'::public.price_type,
      5200,
      4.7::numeric,
      312,
      false
    ),
    (
      'outbound-studio',
      'support-assistant-saas',
      'Support Assistant for SaaS',
      'AI Assistants',
      'AI Assistant - Support',
      'A configured assistant that resolves tier-1 tickets in your tone, with handoff to humans when needed.',
      null,
      array['Support', 'SaaS', 'Assistant']::text[],
      'published'::public.asset_status,
      false,
      39::numeric,
      'paid'::public.price_type,
      640,
      4.8::numeric,
      47,
      false
    ),
    (
      'rank-better',
      'n8n-content-repurpose',
      'n8n Content Repurpose Blueprint',
      'Automation Assets',
      'Automation - Content',
      'Turn one long-form piece into 12 channel-ready posts automatically, every week, without lifting a finger.',
      null,
      array['n8n', 'Repurposing', 'Automation']::text[],
      'published'::public.asset_status,
      false,
      15::numeric,
      'paid'::public.price_type,
      1120,
      4.8::numeric,
      88,
      false
    ),
    (
      'outbound-studio',
      'icp-research-agent',
      'ICP Research Agent',
      'AI Agents',
      'AI Agent - Sales',
      'Build a sharp ICP, enrich target accounts, and pre-write 1:1 personalization for every contact.',
      null,
      array['ICP', 'Sales', 'Research']::text[],
      'published'::public.asset_status,
      false,
      22::numeric,
      'paid'::public.price_type,
      780,
      4.9::numeric,
      64,
      false
    ),
    (
      'growth-lab',
      'shopify-offer-angle-generator',
      'Shopify Offer Angle Generator',
      'Prompts',
      'Prompts - Ecommerce',
      'A prompt system that turns any product into 20 distinct offer angles ready to test as ads.',
      null,
      array['Offers', 'Ads', 'Shopify']::text[],
      'published'::public.asset_status,
      false,
      12::numeric,
      'paid'::public.price_type,
      1980,
      4.9::numeric,
      154,
      false
    ),
    (
      'rank-better',
      'programmatic-seo-template',
      'Programmatic SEO Page Template',
      'Templates',
      'Template - SEO',
      'A production-ready page template and data structure for shipping 1,000+ programmatic pages that rank.',
      null,
      array['Programmatic', 'SEO', 'Templates']::text[],
      'published'::public.asset_status,
      false,
      35::numeric,
      'paid'::public.price_type,
      510,
      4.8::numeric,
      39,
      false
    )
)
insert into public.assets (
  creator_id,
  slug,
  title,
  product_type,
  category,
  short_description,
  long_description,
  tags,
  status,
  is_free,
  price,
  price_type,
  downloads,
  rating,
  review_count,
  featured,
  published_at
)
select
  creators.id,
  asset_seed.slug,
  asset_seed.title,
  asset_seed.product_type,
  asset_seed.category,
  asset_seed.short_description,
  asset_seed.long_description,
  asset_seed.tags,
  asset_seed.status,
  asset_seed.is_free,
  asset_seed.price,
  asset_seed.price_type,
  asset_seed.downloads,
  asset_seed.rating,
  asset_seed.review_count,
  asset_seed.featured,
  now()
from asset_seed
join public.creators on creators.slug = asset_seed.creator_slug
on conflict (slug) do update set
  creator_id = excluded.creator_id,
  title = excluded.title,
  product_type = excluded.product_type,
  category = excluded.category,
  short_description = excluded.short_description,
  long_description = excluded.long_description,
  tags = excluded.tags,
  status = excluded.status,
  is_free = excluded.is_free,
  price = excluded.price,
  price_type = excluded.price_type,
  downloads = excluded.downloads,
  rating = excluded.rating,
  review_count = excluded.review_count,
  featured = excluded.featured,
  published_at = coalesce(public.assets.published_at, excluded.published_at);

commit;
